# Generated by Django 5.2.7 on 2026-01-12 13:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='blog.post')),
            ],
        ),
    ]
