# Generated by Django 5.2.7 on 2026-05-16 21:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_active_alter_comment_parent_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
